### ISSUE TITLE
Package xml2json has no versions

### ISSUE THREAD

**Issue by santoshgistto** [shamblett/xml2json#10]
I am getting following error

Package xml2json has no versions that match >=2.0.11 <3.0.0 derived from:
- flutter_cloud depends on version ^2.0.11
pub get failed (1)

**Comment by shamblett** [comment]
Yes, its because the Dart SDK constraint used in the package is not compatible with Flutter, I've fixed this and re-published the package at version 2.0.12. Please upgrade your package and you should be good to go.

**Comment by santoshgistto** [comment]
@shamblett  thanks for this,
but still am getting 

Package xml2json has no versions that match >=2.0.12 <3.0.0 derived from:
- flutter_cloud depends on version ^2.0.12
pub get failed (1)

**Comment by shamblett** [comment]
Try just setting the version to 2.0.12 specifically also use pub get -v to see more about what pub is trying to do

**Comment by santoshgistto** [comment]
pub get is not working for i used this command   flutter packages get -v
```
       [  +30 ms] [/Users/rd/rd_work/flutter_dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
        [  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
        [        ] origin/beta
        [        ] [/Users/rd/rd_work/flutter_dev/flutter/] git rev-parse --abbrev-ref HEAD
        [  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
        [        ] beta
        [        ] [/Users/rd/rd_work/flutter_dev/flutter/] git ls-remote --get-url origin
        [   +9 ms] Exit code 0 from: git ls-remote --get-url origin
        [        ] https://github.com/flutter/flutter.git
        [        ] [/Users/rd/rd_work/flutter_dev/flutter/] git log -n 1 --pretty=format:%H
        [   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
        [        ] 5a58b36e36b8d7aace89d3950e6deb307956a6a0
        [        ] [/Users/rd/rd_work/flutter_dev/flutter/] git log -n 1 --pretty=format:%ar
        [   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
        [        ] 3 weeks ago
        [   +1 ms] [/Users/rd/rd_work/flutter_dev/flutter/] git describe --match v*.*.* --first-parent --long --tags
        [  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
        [        ] v0.2.3-0-g5a58b36e3
        [ +140 ms] Running "flutter packages get" in flutter_cloud...
        [   +3 ms] [/Users/rd/rd_work/android_sample/flutter_cloud/] /Users/rd/rd_work/flutter_dev/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning --verbose get --no-precompile
        [+1219 ms] Package xml2json has no versions that match 2.0.12 derived from:
        [        ] - flutter_cloud depends on version 2.0.12
        [  +41 ms] "flutter get" took 1,340ms.
        pub get failed (1)

        #0      throwToolExit (package:flutter_tools/src/base/common.dart:28)
        #1      pub (package:flutter_tools/src/dart/pub.dart:168)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104)
<asynchronous suspension>
#3      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:74)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:290)
<asynchronous suspension>
#5      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:228)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:286)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
        #9      new Future.sync (dart:async/future.dart:222)
        #10     CommandRunner.run (package:args/command_runner.dart:109)
        #11     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:166)
        #12     run.<anonymous closure> (package:flutter_tools/runner.dart:90)
<asynchronous suspension>
#13     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#14     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
        #15     _rootRun (dart:async/zone.dart:1126)
        #16     _CustomZone.run (dart:async/zone.dart:1023)
        #17     runZoned (dart:async/zone.dart:1501)
        #18     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
        #19     run (package:flutter_tools/runner.dart:61)
<asynchronous suspension>
#20     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#21     main (file:///Users/rd/rd_work/flutter_dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:16)
        #22     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
        #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


        [  +51 ms] ensureAnalyticsSent: 46ms
        [   +1 ms] Running shutdown hooks
        [        ] Shutdown hooks complete
        [        ] exiting with code 1
```

**Comment by santoshgistto** [comment]
@shamblett  i am able get later version of xml2json after removing this https://pub.dartlang.org/packages/xml package from pubspec 

thanks,
